platform(main, 

         [node(node1, 
               [memory(ram, [family(ram), size(16), alignment(4)]),
                memory(disk, [family(disk), size(1024)])],
               [processor(cpu0, [family(cpu),frequency('2GHz'), schedule(100)]),
                processor(cpu1, [family(cpu),frequency('2GHz'), schedule(100)]),
                processor(cpu2, [family(cpu),frequency('2GHz'), schedule(100)]),
                processor(cpu3, [family(cpu),frequency('2GHz'), schedule(100)])],
               [device(es,
                      [port(p1, [])],
                      [family(ttcard)])],
               [],
               [sk(lynxsecure)]),

          node(node2,
               [memory(ram, [family(ram), size(16), alignment(1)]),
                memory(disk, [family(disk), size(1024)])],
               [processor(cpu0, [family(cpu),frequency('2GHz'), schedule(100)]),
                processor(cpu1, [family(cpu),frequency('2GHz'), schedule(100)]),
                processor(cpu2, [family(cpu),frequency('2GHz'), schedule(100)]),
                processor(cpu3, [family(cpu),frequency('2GHz'), schedule(100)])],
               [device(es,
                      [port(p1, [type(p1)])],
                      [family(ttcard), schedule(100)])],
               [],
               [sk(lynxsecure)])],

         [switch(sw0,
                 [port(p1, []),
                  port(p2, [])],
                 [])],

         [phylink(f1, [node1, es, p1], [sw0, p1], 
                  [length('2m'), media(copper)]),
          phylink(f2, [node2, es, p1], [sw0, p2],
                  [length('2m'), media(copper)])],

         [milsfilename('...')]).
