assert(ac_evidence_counter(10000)).
retractall(ac_evidence_counter(_),1).
assert(ac_evidence_counter(10001)).
assert(ac_evidence(certificate,'CC Evaluation certificate',[],[arg('S',foundational_plane:platform,platform(main,[node(node1,[memory(ram,[family(ram),size(16),alignment(4)]),memory(disk,[family(disk),size(1024)])],[processor(cpu0,[family(cpu),frequency('2GHz'),schedule(100)]),processor(cpu1,[family(cpu),frequency('2GHz'),schedule(100)]),processor(cpu2,[family(cpu),frequency('2GHz'),schedule(100)]),processor(cpu3,[family(cpu),frequency('2GHz'),schedule(100)])],[device(es,[port(p1,[])],[family(ttcard)])],[],[sk(lynxsecure)]),node(node2,[memory(ram,[family(ram),size(16),alignment(1)]),memory(disk,[family(disk),size(1024)])],[processor(cpu0,[family(cpu),frequency('2GHz'),schedule(100)]),processor(cpu1,[family(cpu),frequency('2GHz'),schedule(100)]),processor(cpu2,[family(cpu),frequency('2GHz'),schedule(100)]),processor(cpu3,[family(cpu),frequency('2GHz'),schedule(100)])],[device(es,[port(p1,[type(p1)])],[family(ttcard),schedule(100)])],[],[sk(lynxsecure)])],[switch(sw0,[port(p1,[]),port(p2,[])],[])],[phylink(f1,[node1,es,p1],[sw0,p1],[length('2m'),media(copper)]),phylink(f2,[node2,es,p1],[sw0,p2],[length('2m'),media(copper)])],[milsfilename(...)])),arg('N',foundational_plane:node,node(node1,[memory(ram,[family(ram),size(16),alignment(4)]),memory(disk,[family(disk),size(1024)])],[processor(cpu0,[family(cpu),frequency('2GHz'),schedule(100)]),processor(cpu1,[family(cpu),frequency('2GHz'),schedule(100)]),processor(cpu2,[family(cpu),frequency('2GHz'),schedule(100)]),processor(cpu3,[family(cpu),frequency('2GHz'),schedule(100)])],[device(es,[port(p1,[])],[family(ttcard)])],[],[sk(lynxsecure)]))],10001,pending)).
retractall(ac_evidence(certificate,'CC Evaluation certificate',[],[arg('S',foundational_plane:platform,platform(main,[node(node1,[memory(ram,[family(ram),size(16),alignment(4)]),memory(disk,[family(disk),size(1024)])],[processor(cpu0,[family(cpu),frequency('2GHz'),schedule(100)]),processor(cpu1,[family(cpu),frequency('2GHz'),schedule(100)]),processor(cpu2,[family(cpu),frequency('2GHz'),schedule(100)]),processor(cpu3,[family(cpu),frequency('2GHz'),schedule(100)])],[device(es,[port(p1,[])],[family(ttcard)])],[],[sk(lynxsecure)]),node(node2,[memory(ram,[family(ram),size(16),alignment(1)]),memory(disk,[family(disk),size(1024)])],[processor(cpu0,[family(cpu),frequency('2GHz'),schedule(100)]),processor(cpu1,[family(cpu),frequency('2GHz'),schedule(100)]),processor(cpu2,[family(cpu),frequency('2GHz'),schedule(100)]),processor(cpu3,[family(cpu),frequency('2GHz'),schedule(100)])],[device(es,[port(p1,[type(p1)])],[family(ttcard),schedule(100)])],[],[sk(lynxsecure)])],[switch(sw0,[port(p1,[]),port(p2,[])],[])],[phylink(f1,[node1,es,p1],[sw0,p1],[length('2m'),media(copper)]),phylink(f2,[node2,es,p1],[sw0,p2],[length('2m'),media(copper)])],[milsfilename(...)])),arg('N',foundational_plane:node,node(node1,[memory(ram,[family(ram),size(16),alignment(4)]),memory(disk,[family(disk),size(1024)])],[processor(cpu0,[family(cpu),frequency('2GHz'),schedule(100)]),processor(cpu1,[family(cpu),frequency('2GHz'),schedule(100)]),processor(cpu2,[family(cpu),frequency('2GHz'),schedule(100)]),processor(cpu3,[family(cpu),frequency('2GHz'),schedule(100)])],[device(es,[port(p1,[])],[family(ttcard)])],[],[sk(lynxsecure)]))],10001,_),1).
assert(ac_evidence(certificate,'CC Evaluation certificate',[],[arg('S',foundational_plane:platform,platform(main,[node(node1,[memory(ram,[family(ram),size(16),alignment(4)]),memory(disk,[family(disk),size(1024)])],[processor(cpu0,[family(cpu),frequency('2GHz'),schedule(100)]),processor(cpu1,[family(cpu),frequency('2GHz'),schedule(100)]),processor(cpu2,[family(cpu),frequency('2GHz'),schedule(100)]),processor(cpu3,[family(cpu),frequency('2GHz'),schedule(100)])],[device(es,[port(p1,[])],[family(ttcard)])],[],[sk(lynxsecure)]),node(node2,[memory(ram,[family(ram),size(16),alignment(1)]),memory(disk,[family(disk),size(1024)])],[processor(cpu0,[family(cpu),frequency('2GHz'),schedule(100)]),processor(cpu1,[family(cpu),frequency('2GHz'),schedule(100)]),processor(cpu2,[family(cpu),frequency('2GHz'),schedule(100)]),processor(cpu3,[family(cpu),frequency('2GHz'),schedule(100)])],[device(es,[port(p1,[type(p1)])],[family(ttcard),schedule(100)])],[],[sk(lynxsecure)])],[switch(sw0,[port(p1,[]),port(p2,[])],[])],[phylink(f1,[node1,es,p1],[sw0,p1],[length('2m'),media(copper)]),phylink(f2,[node2,es,p1],[sw0,p2],[length('2m'),media(copper)])],[milsfilename(...)])),arg('N',foundational_plane:node,node(node1,[memory(ram,[family(ram),size(16),alignment(4)]),memory(disk,[family(disk),size(1024)])],[processor(cpu0,[family(cpu),frequency('2GHz'),schedule(100)]),processor(cpu1,[family(cpu),frequency('2GHz'),schedule(100)]),processor(cpu2,[family(cpu),frequency('2GHz'),schedule(100)]),processor(cpu3,[family(cpu),frequency('2GHz'),schedule(100)])],[device(es,[port(p1,[])],[family(ttcard)])],[],[sk(lynxsecure)]))],10001,ongoing)).
retractall(ac_evidence_counter(_),1).
assert(ac_evidence_counter(10002)).
assert(ac_evidence(unknown,'configuration blueprints',[],[arg('S',foundational_plane:platform,platform(main,[node(node1,[memory(ram,[family(ram),size(16),alignment(4)]),memory(disk,[family(disk),size(1024)])],[processor(cpu0,[family(cpu),frequency('2GHz'),schedule(100)]),processor(cpu1,[family(cpu),frequency('2GHz'),schedule(100)]),processor(cpu2,[family(cpu),frequency('2GHz'),schedule(100)]),processor(cpu3,[family(cpu),frequency('2GHz'),schedule(100)])],[device(es,[port(p1,[])],[family(ttcard)])],[],[sk(lynxsecure)]),node(node2,[memory(ram,[family(ram),size(16),alignment(1)]),memory(disk,[family(disk),size(1024)])],[processor(cpu0,[family(cpu),frequency('2GHz'),schedule(100)]),processor(cpu1,[family(cpu),frequency('2GHz'),schedule(100)]),processor(cpu2,[family(cpu),frequency('2GHz'),schedule(100)]),processor(cpu3,[family(cpu),frequency('2GHz'),schedule(100)])],[device(es,[port(p1,[type(p1)])],[family(ttcard),schedule(100)])],[],[sk(lynxsecure)])],[switch(sw0,[port(p1,[]),port(p2,[])],[])],[phylink(f1,[node1,es,p1],[sw0,p1],[length('2m'),media(copper)]),phylink(f2,[node2,es,p1],[sw0,p2],[length('2m'),media(copper)])],[milsfilename(...)])),arg('N',foundational_plane:node,node(node1,[memory(ram,[family(ram),size(16),alignment(4)]),memory(disk,[family(disk),size(1024)])],[processor(cpu0,[family(cpu),frequency('2GHz'),schedule(100)]),processor(cpu1,[family(cpu),frequency('2GHz'),schedule(100)]),processor(cpu2,[family(cpu),frequency('2GHz'),schedule(100)]),processor(cpu3,[family(cpu),frequency('2GHz'),schedule(100)])],[device(es,[port(p1,[])],[family(ttcard)])],[],[sk(lynxsecure)]))],10002,pending)).
retractall(ac_evidence_counter(_),1).
assert(ac_evidence_counter(10003)).
assert(ac_evidence(certificate,'CC Evaluation certificate',[],[arg('S',foundational_plane:platform,platform(main,[node(node1,[memory(ram,[family(ram),size(16),alignment(4)]),memory(disk,[family(disk),size(1024)])],[processor(cpu0,[family(cpu),frequency('2GHz'),schedule(100)]),processor(cpu1,[family(cpu),frequency('2GHz'),schedule(100)]),processor(cpu2,[family(cpu),frequency('2GHz'),schedule(100)]),processor(cpu3,[family(cpu),frequency('2GHz'),schedule(100)])],[device(es,[port(p1,[])],[family(ttcard)])],[],[sk(lynxsecure)]),node(node2,[memory(ram,[family(ram),size(16),alignment(1)]),memory(disk,[family(disk),size(1024)])],[processor(cpu0,[family(cpu),frequency('2GHz'),schedule(100)]),processor(cpu1,[family(cpu),frequency('2GHz'),schedule(100)]),processor(cpu2,[family(cpu),frequency('2GHz'),schedule(100)]),processor(cpu3,[family(cpu),frequency('2GHz'),schedule(100)])],[device(es,[port(p1,[type(p1)])],[family(ttcard),schedule(100)])],[],[sk(lynxsecure)])],[switch(sw0,[port(p1,[]),port(p2,[])],[])],[phylink(f1,[node1,es,p1],[sw0,p1],[length('2m'),media(copper)]),phylink(f2,[node2,es,p1],[sw0,p2],[length('2m'),media(copper)])],[milsfilename(...)])),arg('N',foundational_plane:node,node(node2,[memory(ram,[family(ram),size(16),alignment(1)]),memory(disk,[family(disk),size(1024)])],[processor(cpu0,[family(cpu),frequency('2GHz'),schedule(100)]),processor(cpu1,[family(cpu),frequency('2GHz'),schedule(100)]),processor(cpu2,[family(cpu),frequency('2GHz'),schedule(100)]),processor(cpu3,[family(cpu),frequency('2GHz'),schedule(100)])],[device(es,[port(p1,[type(p1)])],[family(ttcard),schedule(100)])],[],[sk(lynxsecure)]))],10003,pending)).
retractall(ac_evidence(certificate,'CC Evaluation certificate',[],[arg('S',foundational_plane:platform,platform(main,[node(node1,[memory(ram,[family(ram),size(16),alignment(4)]),memory(disk,[family(disk),size(1024)])],[processor(cpu0,[family(cpu),frequency('2GHz'),schedule(100)]),processor(cpu1,[family(cpu),frequency('2GHz'),schedule(100)]),processor(cpu2,[family(cpu),frequency('2GHz'),schedule(100)]),processor(cpu3,[family(cpu),frequency('2GHz'),schedule(100)])],[device(es,[port(p1,[])],[family(ttcard)])],[],[sk(lynxsecure)]),node(node2,[memory(ram,[family(ram),size(16),alignment(1)]),memory(disk,[family(disk),size(1024)])],[processor(cpu0,[family(cpu),frequency('2GHz'),schedule(100)]),processor(cpu1,[family(cpu),frequency('2GHz'),schedule(100)]),processor(cpu2,[family(cpu),frequency('2GHz'),schedule(100)]),processor(cpu3,[family(cpu),frequency('2GHz'),schedule(100)])],[device(es,[port(p1,[type(p1)])],[family(ttcard),schedule(100)])],[],[sk(lynxsecure)])],[switch(sw0,[port(p1,[]),port(p2,[])],[])],[phylink(f1,[node1,es,p1],[sw0,p1],[length('2m'),media(copper)]),phylink(f2,[node2,es,p1],[sw0,p2],[length('2m'),media(copper)])],[milsfilename(...)])),arg('N',foundational_plane:node,node(node2,[memory(ram,[family(ram),size(16),alignment(1)]),memory(disk,[family(disk),size(1024)])],[processor(cpu0,[family(cpu),frequency('2GHz'),schedule(100)]),processor(cpu1,[family(cpu),frequency('2GHz'),schedule(100)]),processor(cpu2,[family(cpu),frequency('2GHz'),schedule(100)]),processor(cpu3,[family(cpu),frequency('2GHz'),schedule(100)])],[device(es,[port(p1,[type(p1)])],[family(ttcard),schedule(100)])],[],[sk(lynxsecure)]))],10003,_),1).
assert(ac_evidence(certificate,'CC Evaluation certificate',[],[arg('S',foundational_plane:platform,platform(main,[node(node1,[memory(ram,[family(ram),size(16),alignment(4)]),memory(disk,[family(disk),size(1024)])],[processor(cpu0,[family(cpu),frequency('2GHz'),schedule(100)]),processor(cpu1,[family(cpu),frequency('2GHz'),schedule(100)]),processor(cpu2,[family(cpu),frequency('2GHz'),schedule(100)]),processor(cpu3,[family(cpu),frequency('2GHz'),schedule(100)])],[device(es,[port(p1,[])],[family(ttcard)])],[],[sk(lynxsecure)]),node(node2,[memory(ram,[family(ram),size(16),alignment(1)]),memory(disk,[family(disk),size(1024)])],[processor(cpu0,[family(cpu),frequency('2GHz'),schedule(100)]),processor(cpu1,[family(cpu),frequency('2GHz'),schedule(100)]),processor(cpu2,[family(cpu),frequency('2GHz'),schedule(100)]),processor(cpu3,[family(cpu),frequency('2GHz'),schedule(100)])],[device(es,[port(p1,[type(p1)])],[family(ttcard),schedule(100)])],[],[sk(lynxsecure)])],[switch(sw0,[port(p1,[]),port(p2,[])],[])],[phylink(f1,[node1,es,p1],[sw0,p1],[length('2m'),media(copper)]),phylink(f2,[node2,es,p1],[sw0,p2],[length('2m'),media(copper)])],[milsfilename(...)])),arg('N',foundational_plane:node,node(node2,[memory(ram,[family(ram),size(16),alignment(1)]),memory(disk,[family(disk),size(1024)])],[processor(cpu0,[family(cpu),frequency('2GHz'),schedule(100)]),processor(cpu1,[family(cpu),frequency('2GHz'),schedule(100)]),processor(cpu2,[family(cpu),frequency('2GHz'),schedule(100)]),processor(cpu3,[family(cpu),frequency('2GHz'),schedule(100)])],[device(es,[port(p1,[type(p1)])],[family(ttcard),schedule(100)])],[],[sk(lynxsecure)]))],10003,ongoing)).
retractall(ac_evidence_counter(_),1).
assert(ac_evidence_counter(10004)).
assert(ac_evidence(unknown,'configuration blueprints',[],[arg('S',foundational_plane:platform,platform(main,[node(node1,[memory(ram,[family(ram),size(16),alignment(4)]),memory(disk,[family(disk),size(1024)])],[processor(cpu0,[family(cpu),frequency('2GHz'),schedule(100)]),processor(cpu1,[family(cpu),frequency('2GHz'),schedule(100)]),processor(cpu2,[family(cpu),frequency('2GHz'),schedule(100)]),processor(cpu3,[family(cpu),frequency('2GHz'),schedule(100)])],[device(es,[port(p1,[])],[family(ttcard)])],[],[sk(lynxsecure)]),node(node2,[memory(ram,[family(ram),size(16),alignment(1)]),memory(disk,[family(disk),size(1024)])],[processor(cpu0,[family(cpu),frequency('2GHz'),schedule(100)]),processor(cpu1,[family(cpu),frequency('2GHz'),schedule(100)]),processor(cpu2,[family(cpu),frequency('2GHz'),schedule(100)]),processor(cpu3,[family(cpu),frequency('2GHz'),schedule(100)])],[device(es,[port(p1,[type(p1)])],[family(ttcard),schedule(100)])],[],[sk(lynxsecure)])],[switch(sw0,[port(p1,[]),port(p2,[])],[])],[phylink(f1,[node1,es,p1],[sw0,p1],[length('2m'),media(copper)]),phylink(f2,[node2,es,p1],[sw0,p2],[length('2m'),media(copper)])],[milsfilename(...)])),arg('N',foundational_plane:node,node(node2,[memory(ram,[family(ram),size(16),alignment(1)]),memory(disk,[family(disk),size(1024)])],[processor(cpu0,[family(cpu),frequency('2GHz'),schedule(100)]),processor(cpu1,[family(cpu),frequency('2GHz'),schedule(100)]),processor(cpu2,[family(cpu),frequency('2GHz'),schedule(100)]),processor(cpu3,[family(cpu),frequency('2GHz'),schedule(100)])],[device(es,[port(p1,[type(p1)])],[family(ttcard),schedule(100)])],[],[sk(lynxsecure)]))],10004,pending)).
retractall(ac_evidence_counter(_),1).
assert(ac_evidence_counter(10005)).
assert(ac_evidence(unknown,'Formal verification results for the reconfiguration request protocol',[],[arg('S',foundational_plane:platform,platform(main,[node(node1,[memory(ram,[family(ram),size(16),alignment(4)]),memory(disk,[family(disk),size(1024)])],[processor(cpu0,[family(cpu),frequency('2GHz'),schedule(100)]),processor(cpu1,[family(cpu),frequency('2GHz'),schedule(100)]),processor(cpu2,[family(cpu),frequency('2GHz'),schedule(100)]),processor(cpu3,[family(cpu),frequency('2GHz'),schedule(100)])],[device(es,[port(p1,[])],[family(ttcard)])],[],[sk(lynxsecure)]),node(node2,[memory(ram,[family(ram),size(16),alignment(1)]),memory(disk,[family(disk),size(1024)])],[processor(cpu0,[family(cpu),frequency('2GHz'),schedule(100)]),processor(cpu1,[family(cpu),frequency('2GHz'),schedule(100)]),processor(cpu2,[family(cpu),frequency('2GHz'),schedule(100)]),processor(cpu3,[family(cpu),frequency('2GHz'),schedule(100)])],[device(es,[port(p1,[type(p1)])],[family(ttcard),schedule(100)])],[],[sk(lynxsecure)])],[switch(sw0,[port(p1,[]),port(p2,[])],[])],[phylink(f1,[node1,es,p1],[sw0,p1],[length('2m'),media(copper)]),phylink(f2,[node2,es,p1],[sw0,p2],[length('2m'),media(copper)])],[milsfilename(...)]))],10005,pending)).
retractall(ac_evidence_counter(_),1).
assert(ac_evidence_counter(10006)).
assert(ac_evidence(unknown,'Formal verification results for TSN schedule distribution protocol',[],[arg('S',foundational_plane:platform,platform(main,[node(node1,[memory(ram,[family(ram),size(16),alignment(4)]),memory(disk,[family(disk),size(1024)])],[processor(cpu0,[family(cpu),frequency('2GHz'),schedule(100)]),processor(cpu1,[family(cpu),frequency('2GHz'),schedule(100)]),processor(cpu2,[family(cpu),frequency('2GHz'),schedule(100)]),processor(cpu3,[family(cpu),frequency('2GHz'),schedule(100)])],[device(es,[port(p1,[])],[family(ttcard)])],[],[sk(lynxsecure)]),node(node2,[memory(ram,[family(ram),size(16),alignment(1)]),memory(disk,[family(disk),size(1024)])],[processor(cpu0,[family(cpu),frequency('2GHz'),schedule(100)]),processor(cpu1,[family(cpu),frequency('2GHz'),schedule(100)]),processor(cpu2,[family(cpu),frequency('2GHz'),schedule(100)]),processor(cpu3,[family(cpu),frequency('2GHz'),schedule(100)])],[device(es,[port(p1,[type(p1)])],[family(ttcard),schedule(100)])],[],[sk(lynxsecure)])],[switch(sw0,[port(p1,[]),port(p2,[])],[])],[phylink(f1,[node1,es,p1],[sw0,p1],[length('2m'),media(copper)]),phylink(f2,[node2,es,p1],[sw0,p2],[length('2m'),media(copper)])],[milsfilename(...)]))],10006,pending)).
retractall(ac_evidence_counter(_),1).
assert(ac_evidence_counter(10007)).
assert(ac_evidence(unknown,'TSN high integrity switch design',[],[arg('S',foundational_plane:platform,platform(main,[node(node1,[memory(ram,[family(ram),size(16),alignment(4)]),memory(disk,[family(disk),size(1024)])],[processor(cpu0,[family(cpu),frequency('2GHz'),schedule(100)]),processor(cpu1,[family(cpu),frequency('2GHz'),schedule(100)]),processor(cpu2,[family(cpu),frequency('2GHz'),schedule(100)]),processor(cpu3,[family(cpu),frequency('2GHz'),schedule(100)])],[device(es,[port(p1,[])],[family(ttcard)])],[],[sk(lynxsecure)]),node(node2,[memory(ram,[family(ram),size(16),alignment(1)]),memory(disk,[family(disk),size(1024)])],[processor(cpu0,[family(cpu),frequency('2GHz'),schedule(100)]),processor(cpu1,[family(cpu),frequency('2GHz'),schedule(100)]),processor(cpu2,[family(cpu),frequency('2GHz'),schedule(100)]),processor(cpu3,[family(cpu),frequency('2GHz'),schedule(100)])],[device(es,[port(p1,[type(p1)])],[family(ttcard),schedule(100)])],[],[sk(lynxsecure)])],[switch(sw0,[port(p1,[]),port(p2,[])],[])],[phylink(f1,[node1,es,p1],[sw0,p1],[length('2m'),media(copper)]),phylink(f2,[node2,es,p1],[sw0,p2],[length('2m'),media(copper)])],[milsfilename(...)]))],10007,pending)).
retractall(ac_evidence_counter(_),1).
assert(ac_evidence_counter(10008)).
assert(ac_evidence(unknown,'TSN high integrity endpoint card design',[],[arg('S',foundational_plane:platform,platform(main,[node(node1,[memory(ram,[family(ram),size(16),alignment(4)]),memory(disk,[family(disk),size(1024)])],[processor(cpu0,[family(cpu),frequency('2GHz'),schedule(100)]),processor(cpu1,[family(cpu),frequency('2GHz'),schedule(100)]),processor(cpu2,[family(cpu),frequency('2GHz'),schedule(100)]),processor(cpu3,[family(cpu),frequency('2GHz'),schedule(100)])],[device(es,[port(p1,[])],[family(ttcard)])],[],[sk(lynxsecure)]),node(node2,[memory(ram,[family(ram),size(16),alignment(1)]),memory(disk,[family(disk),size(1024)])],[processor(cpu0,[family(cpu),frequency('2GHz'),schedule(100)]),processor(cpu1,[family(cpu),frequency('2GHz'),schedule(100)]),processor(cpu2,[family(cpu),frequency('2GHz'),schedule(100)]),processor(cpu3,[family(cpu),frequency('2GHz'),schedule(100)])],[device(es,[port(p1,[type(p1)])],[family(ttcard),schedule(100)])],[],[sk(lynxsecure)])],[switch(sw0,[port(p1,[]),port(p2,[])],[])],[phylink(f1,[node1,es,p1],[sw0,p1],[length('2m'),media(copper)]),phylink(f2,[node2,es,p1],[sw0,p2],[length('2m'),media(copper)])],[milsfilename(...)]))],10008,pending)).
retractall(ac_evidence_counter(_),1).
assert(ac_evidence_counter(10009)).
assert(ac_evidence(unknown,'TSN network design',[],[arg('S',foundational_plane:platform,platform(main,[node(node1,[memory(ram,[family(ram),size(16),alignment(4)]),memory(disk,[family(disk),size(1024)])],[processor(cpu0,[family(cpu),frequency('2GHz'),schedule(100)]),processor(cpu1,[family(cpu),frequency('2GHz'),schedule(100)]),processor(cpu2,[family(cpu),frequency('2GHz'),schedule(100)]),processor(cpu3,[family(cpu),frequency('2GHz'),schedule(100)])],[device(es,[port(p1,[])],[family(ttcard)])],[],[sk(lynxsecure)]),node(node2,[memory(ram,[family(ram),size(16),alignment(1)]),memory(disk,[family(disk),size(1024)])],[processor(cpu0,[family(cpu),frequency('2GHz'),schedule(100)]),processor(cpu1,[family(cpu),frequency('2GHz'),schedule(100)]),processor(cpu2,[family(cpu),frequency('2GHz'),schedule(100)]),processor(cpu3,[family(cpu),frequency('2GHz'),schedule(100)])],[device(es,[port(p1,[type(p1)])],[family(ttcard),schedule(100)])],[],[sk(lynxsecure)])],[switch(sw0,[port(p1,[]),port(p2,[])],[])],[phylink(f1,[node1,es,p1],[sw0,p1],[length('2m'),media(copper)]),phylink(f2,[node2,es,p1],[sw0,p2],[length('2m'),media(copper)])],[milsfilename(...)]))],10009,pending)).
retractall(ac_evidence_counter(_),1).
assert(ac_evidence_counter(10010)).
assert(ac_evidence(unknown,'Results of network fault propagation analysis',[],[arg('S',foundational_plane:platform,platform(main,[node(node1,[memory(ram,[family(ram),size(16),alignment(4)]),memory(disk,[family(disk),size(1024)])],[processor(cpu0,[family(cpu),frequency('2GHz'),schedule(100)]),processor(cpu1,[family(cpu),frequency('2GHz'),schedule(100)]),processor(cpu2,[family(cpu),frequency('2GHz'),schedule(100)]),processor(cpu3,[family(cpu),frequency('2GHz'),schedule(100)])],[device(es,[port(p1,[])],[family(ttcard)])],[],[sk(lynxsecure)]),node(node2,[memory(ram,[family(ram),size(16),alignment(1)]),memory(disk,[family(disk),size(1024)])],[processor(cpu0,[family(cpu),frequency('2GHz'),schedule(100)]),processor(cpu1,[family(cpu),frequency('2GHz'),schedule(100)]),processor(cpu2,[family(cpu),frequency('2GHz'),schedule(100)]),processor(cpu3,[family(cpu),frequency('2GHz'),schedule(100)])],[device(es,[port(p1,[type(p1)])],[family(ttcard),schedule(100)])],[],[sk(lynxsecure)])],[switch(sw0,[port(p1,[]),port(p2,[])],[])],[phylink(f1,[node1,es,p1],[sw0,p1],[length('2m'),media(copper)]),phylink(f2,[node2,es,p1],[sw0,p2],[length('2m'),media(copper)])],[milsfilename(...)]))],10010,pending)).
retractall(ac_evidence_counter(_),1).
assert(ac_evidence_counter(10011)).
assert(ac_evidence(unknown,'Formal verification results for permanence function',[],[arg('S',foundational_plane:platform,platform(main,[node(node1,[memory(ram,[family(ram),size(16),alignment(4)]),memory(disk,[family(disk),size(1024)])],[processor(cpu0,[family(cpu),frequency('2GHz'),schedule(100)]),processor(cpu1,[family(cpu),frequency('2GHz'),schedule(100)]),processor(cpu2,[family(cpu),frequency('2GHz'),schedule(100)]),processor(cpu3,[family(cpu),frequency('2GHz'),schedule(100)])],[device(es,[port(p1,[])],[family(ttcard)])],[],[sk(lynxsecure)]),node(node2,[memory(ram,[family(ram),size(16),alignment(1)]),memory(disk,[family(disk),size(1024)])],[processor(cpu0,[family(cpu),frequency('2GHz'),schedule(100)]),processor(cpu1,[family(cpu),frequency('2GHz'),schedule(100)]),processor(cpu2,[family(cpu),frequency('2GHz'),schedule(100)]),processor(cpu3,[family(cpu),frequency('2GHz'),schedule(100)])],[device(es,[port(p1,[type(p1)])],[family(ttcard),schedule(100)])],[],[sk(lynxsecure)])],[switch(sw0,[port(p1,[]),port(p2,[])],[])],[phylink(f1,[node1,es,p1],[sw0,p1],[length('2m'),media(copper)]),phylink(f2,[node2,es,p1],[sw0,p2],[length('2m'),media(copper)])],[milsfilename(...)]))],10011,pending)).
retractall(ac_evidence_counter(_),1).
assert(ac_evidence_counter(10012)).
assert(ac_evidence(unknown,'Formal verification results for clock synchronization',[],[arg('S',foundational_plane:platform,platform(main,[node(node1,[memory(ram,[family(ram),size(16),alignment(4)]),memory(disk,[family(disk),size(1024)])],[processor(cpu0,[family(cpu),frequency('2GHz'),schedule(100)]),processor(cpu1,[family(cpu),frequency('2GHz'),schedule(100)]),processor(cpu2,[family(cpu),frequency('2GHz'),schedule(100)]),processor(cpu3,[family(cpu),frequency('2GHz'),schedule(100)])],[device(es,[port(p1,[])],[family(ttcard)])],[],[sk(lynxsecure)]),node(node2,[memory(ram,[family(ram),size(16),alignment(1)]),memory(disk,[family(disk),size(1024)])],[processor(cpu0,[family(cpu),frequency('2GHz'),schedule(100)]),processor(cpu1,[family(cpu),frequency('2GHz'),schedule(100)]),processor(cpu2,[family(cpu),frequency('2GHz'),schedule(100)]),processor(cpu3,[family(cpu),frequency('2GHz'),schedule(100)])],[device(es,[port(p1,[type(p1)])],[family(ttcard),schedule(100)])],[],[sk(lynxsecure)])],[switch(sw0,[port(p1,[]),port(p2,[])],[])],[phylink(f1,[node1,es,p1],[sw0,p1],[length('2m'),media(copper)]),phylink(f2,[node2,es,p1],[sw0,p2],[length('2m'),media(copper)])],[milsfilename(...)]))],10012,pending)).
retractall(ac_evidence_counter(_),1).
assert(ac_evidence_counter(10013)).
assert(ac_evidence(unknown,'Formal verification results',[],[arg('S',foundational_plane:platform,platform(main,[node(node1,[memory(ram,[family(ram),size(16),alignment(4)]),memory(disk,[family(disk),size(1024)])],[processor(cpu0,[family(cpu),frequency('2GHz'),schedule(100)]),processor(cpu1,[family(cpu),frequency('2GHz'),schedule(100)]),processor(cpu2,[family(cpu),frequency('2GHz'),schedule(100)]),processor(cpu3,[family(cpu),frequency('2GHz'),schedule(100)])],[device(es,[port(p1,[])],[family(ttcard)])],[],[sk(lynxsecure)]),node(node2,[memory(ram,[family(ram),size(16),alignment(1)]),memory(disk,[family(disk),size(1024)])],[processor(cpu0,[family(cpu),frequency('2GHz'),schedule(100)]),processor(cpu1,[family(cpu),frequency('2GHz'),schedule(100)]),processor(cpu2,[family(cpu),frequency('2GHz'),schedule(100)]),processor(cpu3,[family(cpu),frequency('2GHz'),schedule(100)])],[device(es,[port(p1,[type(p1)])],[family(ttcard),schedule(100)])],[],[sk(lynxsecure)])],[switch(sw0,[port(p1,[]),port(p2,[])],[])],[phylink(f1,[node1,es,p1],[sw0,p1],[length('2m'),media(copper)]),phylink(f2,[node2,es,p1],[sw0,p2],[length('2m'),media(copper)])],[milsfilename(...)]))],10013,pending)).
retractall(ac_evidence_counter(_),1).
assert(ac_evidence_counter(10014)).
assert(ac_evidence(unknown,'evidence of satisfaction of {availability} on {main}',[],[arg('Policy',operational_plane:policy,policy(main,[subject('S1',[port(p,[],[])],[],[processor(x,[family(cpu),frequency('2GHz'),schedule(70)]),memory(z,[family(ram),size(1)])]),subject(s2,[port(p,[],[])],[],[processor(x,[family(cpu),frequency('2GHz'),schedule(80)]),memory(z,[family(ram),size(5)])])],[object(o1,[],[memory(u,[family(ram),size(3)])]),object(o2,[],[memory(u,[family(ram),size(6)])])],[ss_flow(s1s2,['S1',p],[s2,p],[],[])],[so_flow(s1o1,'S1',o1,[],[]),so_flow(s2o2,s2,o2,[],[])],[milsfilename('x.mils')],[deployment(not_same(['S1',s2]))])),arg('Requirement',operational_plane:interface_requirement,availability)],10014,pending)).
retractall(ac_evidence_counter(_),1).
assert(ac_evidence_counter(10015)).
assert(ac_evidence(unknown,'evidence of satisfaction of {reliability} on {main}',[],[arg('Policy',operational_plane:policy,policy(main,[subject('S1',[port(p,[],[])],[],[processor(x,[family(cpu),frequency('2GHz'),schedule(70)]),memory(z,[family(ram),size(1)])]),subject(s2,[port(p,[],[])],[],[processor(x,[family(cpu),frequency('2GHz'),schedule(80)]),memory(z,[family(ram),size(5)])])],[object(o1,[],[memory(u,[family(ram),size(3)])]),object(o2,[],[memory(u,[family(ram),size(6)])])],[ss_flow(s1s2,['S1',p],[s2,p],[],[])],[so_flow(s1o1,'S1',o1,[],[]),so_flow(s2o2,s2,o2,[],[])],[milsfilename('x.mils')],[deployment(not_same(['S1',s2]))])),arg('Requirement',operational_plane:interface_requirement,reliability)],10015,pending)).
retractall(ac_evidence_counter(_),1).
assert(ac_evidence_counter(10016)).
assert(ac_evidence(unknown,'Nodes and network configuration',[],[arg('Policy',operational_plane:policy,policy(main,[subject('S1',[port(p,[],[])],[],[processor(x,[family(cpu),frequency('2GHz'),schedule(70)]),memory(z,[family(ram),size(1)])]),subject(s2,[port(p,[],[])],[],[processor(x,[family(cpu),frequency('2GHz'),schedule(80)]),memory(z,[family(ram),size(5)])])],[object(o1,[],[memory(u,[family(ram),size(3)])]),object(o2,[],[memory(u,[family(ram),size(6)])])],[ss_flow(s1s2,['S1',p],[s2,p],[],[])],[so_flow(s1o1,'S1',o1,[],[]),so_flow(s2o2,s2,o2,[],[])],[milsfilename('x.mils')],[deployment(not_same(['S1',s2]))])),arg('Flow',operational_plane:flow,ss_flow(s1s2,['S1',p],[s2,p],[],[]))],10016,pending)).
retractall(ac_evidence_counter(_),1).
assert(ac_evidence_counter(10017)).
assert(ac_evidence(unknown,'Nodes and network configuration',[],[arg('Policy',operational_plane:policy,policy(main,[subject('S1',[port(p,[],[])],[],[processor(x,[family(cpu),frequency('2GHz'),schedule(70)]),memory(z,[family(ram),size(1)])]),subject(s2,[port(p,[],[])],[],[processor(x,[family(cpu),frequency('2GHz'),schedule(80)]),memory(z,[family(ram),size(5)])])],[object(o1,[],[memory(u,[family(ram),size(3)])]),object(o2,[],[memory(u,[family(ram),size(6)])])],[ss_flow(s1s2,['S1',p],[s2,p],[],[])],[so_flow(s1o1,'S1',o1,[],[]),so_flow(s2o2,s2,o2,[],[])],[milsfilename('x.mils')],[deployment(not_same(['S1',s2]))]))],10017,pending)).
retractall(ac_evidence_counter(_),1).
assert(ac_evidence_counter(10018)).
assert(ac_evidence(unknown,'evidence of satisfaction of the mode requirements',[],[arg('Component',operational_plane:component,subject('S1',[port(p,[],[])],[],[processor(x,[family(cpu),frequency('2GHz'),schedule(70)]),memory(z,[family(ram),size(1)])])),arg('Policy',operational_plane:policy,policy(main,[subject('S1',[port(p,[],[])],[],[processor(x,[family(cpu),frequency('2GHz'),schedule(70)]),memory(z,[family(ram),size(1)])]),subject(s2,[port(p,[],[])],[],[processor(x,[family(cpu),frequency('2GHz'),schedule(80)]),memory(z,[family(ram),size(5)])])],[object(o1,[],[memory(u,[family(ram),size(3)])]),object(o2,[],[memory(u,[family(ram),size(6)])])],[ss_flow(s1s2,['S1',p],[s2,p],[],[])],[so_flow(s1o1,'S1',o1,[],[]),so_flow(s2o2,s2,o2,[],[])],[milsfilename('x.mils')],[deployment(not_same(['S1',s2]))])),arg('Mode',operational_plane:component_mode,'a-mode')],10018,pending)).
retractall(ac_evidence_counter(_),1).
assert(ac_evidence_counter(10019)).
assert(ac_evidence(unknown,'evidence of satisfaction of mode transition requirements',[],[arg('Component',operational_plane:component,subject('S1',[port(p,[],[])],[],[processor(x,[family(cpu),frequency('2GHz'),schedule(70)]),memory(z,[family(ram),size(1)])])),arg('Policy',operational_plane:policy,policy(main,[subject('S1',[port(p,[],[])],[],[processor(x,[family(cpu),frequency('2GHz'),schedule(70)]),memory(z,[family(ram),size(1)])]),subject(s2,[port(p,[],[])],[],[processor(x,[family(cpu),frequency('2GHz'),schedule(80)]),memory(z,[family(ram),size(5)])])],[object(o1,[],[memory(u,[family(ram),size(3)])]),object(o2,[],[memory(u,[family(ram),size(6)])])],[ss_flow(s1s2,['S1',p],[s2,p],[],[])],[so_flow(s1o1,'S1',o1,[],[]),so_flow(s2o2,s2,o2,[],[])],[milsfilename('x.mils')],[deployment(not_same(['S1',s2]))])),arg('Transition',operational_plane:component_transition,'a-transition')],10019,pending)).
retractall(ac_evidence_counter(_),1).
assert(ac_evidence_counter(10020)).
assert(ac_evidence(unknown,'evidence of satisfactory error behavior during errors',[],[arg('Component',operational_plane:component,subject('S1',[port(p,[],[])],[],[processor(x,[family(cpu),frequency('2GHz'),schedule(70)]),memory(z,[family(ram),size(1)])])),arg('Policy',operational_plane:policy,policy(main,[subject('S1',[port(p,[],[])],[],[processor(x,[family(cpu),frequency('2GHz'),schedule(70)]),memory(z,[family(ram),size(1)])]),subject(s2,[port(p,[],[])],[],[processor(x,[family(cpu),frequency('2GHz'),schedule(80)]),memory(z,[family(ram),size(5)])])],[object(o1,[],[memory(u,[family(ram),size(3)])]),object(o2,[],[memory(u,[family(ram),size(6)])])],[ss_flow(s1s2,['S1',p],[s2,p],[],[])],[so_flow(s1o1,'S1',o1,[],[]),so_flow(s2o2,s2,o2,[],[])],[milsfilename('x.mils')],[deployment(not_same(['S1',s2]))])),arg('Transition',operational_plane:component_transition,'a-transition')],10020,pending)).
retractall(ac_evidence_counter(_),1).
assert(ac_evidence_counter(10021)).
assert(ac_evidence(unknown,'{Technical failure} specific mitigation',[],[arg('Component',operational_plane:component,subject('S1',[port(p,[],[])],[],[processor(x,[family(cpu),frequency('2GHz'),schedule(70)]),memory(z,[family(ram),size(1)])])),arg('Policy',operational_plane:policy,policy(main,[subject('S1',[port(p,[],[])],[],[processor(x,[family(cpu),frequency('2GHz'),schedule(70)]),memory(z,[family(ram),size(1)])]),subject(s2,[port(p,[],[])],[],[processor(x,[family(cpu),frequency('2GHz'),schedule(80)]),memory(z,[family(ram),size(5)])])],[object(o1,[],[memory(u,[family(ram),size(3)])]),object(o2,[],[memory(u,[family(ram),size(6)])])],[ss_flow(s1s2,['S1',p],[s2,p],[],[])],[so_flow(s1o1,'S1',o1,[],[]),so_flow(s2o2,s2,o2,[],[])],[milsfilename('x.mils')],[deployment(not_same(['S1',s2]))])),arg('Threat',operational_plane:process_threat,'Technical failure')],10021,pending)).
retractall(ac_evidence_counter(_),1).
assert(ac_evidence_counter(10022)).
assert(ac_evidence(unknown,'Evidence that controls are in place',[],[arg('Component',operational_plane:component,subject('S1',[port(p,[],[])],[],[processor(x,[family(cpu),frequency('2GHz'),schedule(70)]),memory(z,[family(ram),size(1)])])),arg('Policy',operational_plane:policy,policy(main,[subject('S1',[port(p,[],[])],[],[processor(x,[family(cpu),frequency('2GHz'),schedule(70)]),memory(z,[family(ram),size(1)])]),subject(s2,[port(p,[],[])],[],[processor(x,[family(cpu),frequency('2GHz'),schedule(80)]),memory(z,[family(ram),size(5)])])],[object(o1,[],[memory(u,[family(ram),size(3)])]),object(o2,[],[memory(u,[family(ram),size(6)])])],[ss_flow(s1s2,['S1',p],[s2,p],[],[])],[so_flow(s1o1,'S1',o1,[],[]),so_flow(s2o2,s2,o2,[],[])],[milsfilename('x.mils')],[deployment(not_same(['S1',s2]))])),arg('Threat',operational_plane:process_threat,'Technical failure')],10022,pending)).
retractall(ac_evidence_counter(_),1).
assert(ac_evidence_counter(10023)).
assert(ac_evidence(unknown,'{Unauthorised action} specific mitigation',[],[arg('Component',operational_plane:component,subject('S1',[port(p,[],[])],[],[processor(x,[family(cpu),frequency('2GHz'),schedule(70)]),memory(z,[family(ram),size(1)])])),arg('Policy',operational_plane:policy,policy(main,[subject('S1',[port(p,[],[])],[],[processor(x,[family(cpu),frequency('2GHz'),schedule(70)]),memory(z,[family(ram),size(1)])]),subject(s2,[port(p,[],[])],[],[processor(x,[family(cpu),frequency('2GHz'),schedule(80)]),memory(z,[family(ram),size(5)])])],[object(o1,[],[memory(u,[family(ram),size(3)])]),object(o2,[],[memory(u,[family(ram),size(6)])])],[ss_flow(s1s2,['S1',p],[s2,p],[],[])],[so_flow(s1o1,'S1',o1,[],[]),so_flow(s2o2,s2,o2,[],[])],[milsfilename('x.mils')],[deployment(not_same(['S1',s2]))])),arg('Threat',operational_plane:process_threat,'Unauthorised action')],10023,pending)).
retractall(ac_evidence_counter(_),1).
assert(ac_evidence_counter(10024)).
assert(ac_evidence(unknown,'Evidence that controls are in place',[],[arg('Component',operational_plane:component,subject('S1',[port(p,[],[])],[],[processor(x,[family(cpu),frequency('2GHz'),schedule(70)]),memory(z,[family(ram),size(1)])])),arg('Policy',operational_plane:policy,policy(main,[subject('S1',[port(p,[],[])],[],[processor(x,[family(cpu),frequency('2GHz'),schedule(70)]),memory(z,[family(ram),size(1)])]),subject(s2,[port(p,[],[])],[],[processor(x,[family(cpu),frequency('2GHz'),schedule(80)]),memory(z,[family(ram),size(5)])])],[object(o1,[],[memory(u,[family(ram),size(3)])]),object(o2,[],[memory(u,[family(ram),size(6)])])],[ss_flow(s1s2,['S1',p],[s2,p],[],[])],[so_flow(s1o1,'S1',o1,[],[]),so_flow(s2o2,s2,o2,[],[])],[milsfilename('x.mils')],[deployment(not_same(['S1',s2]))])),arg('Threat',operational_plane:process_threat,'Unauthorised action')],10024,pending)).
retractall(ac_evidence_counter(_),1).
assert(ac_evidence_counter(10025)).
assert(ac_evidence(unknown,'evidence of satisfaction of the mode requirements',[],[arg('Component',operational_plane:component,subject(s2,[port(p,[],[])],[],[processor(x,[family(cpu),frequency('2GHz'),schedule(80)]),memory(z,[family(ram),size(5)])])),arg('Policy',operational_plane:policy,policy(main,[subject('S1',[port(p,[],[])],[],[processor(x,[family(cpu),frequency('2GHz'),schedule(70)]),memory(z,[family(ram),size(1)])]),subject(s2,[port(p,[],[])],[],[processor(x,[family(cpu),frequency('2GHz'),schedule(80)]),memory(z,[family(ram),size(5)])])],[object(o1,[],[memory(u,[family(ram),size(3)])]),object(o2,[],[memory(u,[family(ram),size(6)])])],[ss_flow(s1s2,['S1',p],[s2,p],[],[])],[so_flow(s1o1,'S1',o1,[],[]),so_flow(s2o2,s2,o2,[],[])],[milsfilename('x.mils')],[deployment(not_same(['S1',s2]))])),arg('Mode',operational_plane:component_mode,'a-mode')],10025,pending)).
retractall(ac_evidence_counter(_),1).
assert(ac_evidence_counter(10026)).
assert(ac_evidence(unknown,'evidence of satisfaction of mode transition requirements',[],[arg('Component',operational_plane:component,subject(s2,[port(p,[],[])],[],[processor(x,[family(cpu),frequency('2GHz'),schedule(80)]),memory(z,[family(ram),size(5)])])),arg('Policy',operational_plane:policy,policy(main,[subject('S1',[port(p,[],[])],[],[processor(x,[family(cpu),frequency('2GHz'),schedule(70)]),memory(z,[family(ram),size(1)])]),subject(s2,[port(p,[],[])],[],[processor(x,[family(cpu),frequency('2GHz'),schedule(80)]),memory(z,[family(ram),size(5)])])],[object(o1,[],[memory(u,[family(ram),size(3)])]),object(o2,[],[memory(u,[family(ram),size(6)])])],[ss_flow(s1s2,['S1',p],[s2,p],[],[])],[so_flow(s1o1,'S1',o1,[],[]),so_flow(s2o2,s2,o2,[],[])],[milsfilename('x.mils')],[deployment(not_same(['S1',s2]))])),arg('Transition',operational_plane:component_transition,'a-transition')],10026,pending)).
retractall(ac_evidence_counter(_),1).
assert(ac_evidence_counter(10027)).
assert(ac_evidence(unknown,'evidence of satisfactory error behavior during errors',[],[arg('Component',operational_plane:component,subject(s2,[port(p,[],[])],[],[processor(x,[family(cpu),frequency('2GHz'),schedule(80)]),memory(z,[family(ram),size(5)])])),arg('Policy',operational_plane:policy,policy(main,[subject('S1',[port(p,[],[])],[],[processor(x,[family(cpu),frequency('2GHz'),schedule(70)]),memory(z,[family(ram),size(1)])]),subject(s2,[port(p,[],[])],[],[processor(x,[family(cpu),frequency('2GHz'),schedule(80)]),memory(z,[family(ram),size(5)])])],[object(o1,[],[memory(u,[family(ram),size(3)])]),object(o2,[],[memory(u,[family(ram),size(6)])])],[ss_flow(s1s2,['S1',p],[s2,p],[],[])],[so_flow(s1o1,'S1',o1,[],[]),so_flow(s2o2,s2,o2,[],[])],[milsfilename('x.mils')],[deployment(not_same(['S1',s2]))])),arg('Transition',operational_plane:component_transition,'a-transition')],10027,pending)).
retractall(ac_evidence_counter(_),1).
assert(ac_evidence_counter(10028)).
assert(ac_evidence(unknown,'{Technical failure} specific mitigation',[],[arg('Component',operational_plane:component,subject(s2,[port(p,[],[])],[],[processor(x,[family(cpu),frequency('2GHz'),schedule(80)]),memory(z,[family(ram),size(5)])])),arg('Policy',operational_plane:policy,policy(main,[subject('S1',[port(p,[],[])],[],[processor(x,[family(cpu),frequency('2GHz'),schedule(70)]),memory(z,[family(ram),size(1)])]),subject(s2,[port(p,[],[])],[],[processor(x,[family(cpu),frequency('2GHz'),schedule(80)]),memory(z,[family(ram),size(5)])])],[object(o1,[],[memory(u,[family(ram),size(3)])]),object(o2,[],[memory(u,[family(ram),size(6)])])],[ss_flow(s1s2,['S1',p],[s2,p],[],[])],[so_flow(s1o1,'S1',o1,[],[]),so_flow(s2o2,s2,o2,[],[])],[milsfilename('x.mils')],[deployment(not_same(['S1',s2]))])),arg('Threat',operational_plane:process_threat,'Technical failure')],10028,pending)).
retractall(ac_evidence_counter(_),1).
assert(ac_evidence_counter(10029)).
assert(ac_evidence(unknown,'Evidence that controls are in place',[],[arg('Component',operational_plane:component,subject(s2,[port(p,[],[])],[],[processor(x,[family(cpu),frequency('2GHz'),schedule(80)]),memory(z,[family(ram),size(5)])])),arg('Policy',operational_plane:policy,policy(main,[subject('S1',[port(p,[],[])],[],[processor(x,[family(cpu),frequency('2GHz'),schedule(70)]),memory(z,[family(ram),size(1)])]),subject(s2,[port(p,[],[])],[],[processor(x,[family(cpu),frequency('2GHz'),schedule(80)]),memory(z,[family(ram),size(5)])])],[object(o1,[],[memory(u,[family(ram),size(3)])]),object(o2,[],[memory(u,[family(ram),size(6)])])],[ss_flow(s1s2,['S1',p],[s2,p],[],[])],[so_flow(s1o1,'S1',o1,[],[]),so_flow(s2o2,s2,o2,[],[])],[milsfilename('x.mils')],[deployment(not_same(['S1',s2]))])),arg('Threat',operational_plane:process_threat,'Technical failure')],10029,pending)).
retractall(ac_evidence_counter(_),1).
assert(ac_evidence_counter(10030)).
assert(ac_evidence(unknown,'{Unauthorised action} specific mitigation',[],[arg('Component',operational_plane:component,subject(s2,[port(p,[],[])],[],[processor(x,[family(cpu),frequency('2GHz'),schedule(80)]),memory(z,[family(ram),size(5)])])),arg('Policy',operational_plane:policy,policy(main,[subject('S1',[port(p,[],[])],[],[processor(x,[family(cpu),frequency('2GHz'),schedule(70)]),memory(z,[family(ram),size(1)])]),subject(s2,[port(p,[],[])],[],[processor(x,[family(cpu),frequency('2GHz'),schedule(80)]),memory(z,[family(ram),size(5)])])],[object(o1,[],[memory(u,[family(ram),size(3)])]),object(o2,[],[memory(u,[family(ram),size(6)])])],[ss_flow(s1s2,['S1',p],[s2,p],[],[])],[so_flow(s1o1,'S1',o1,[],[]),so_flow(s2o2,s2,o2,[],[])],[milsfilename('x.mils')],[deployment(not_same(['S1',s2]))])),arg('Threat',operational_plane:process_threat,'Unauthorised action')],10030,pending)).
retractall(ac_evidence_counter(_),1).
assert(ac_evidence_counter(10031)).
assert(ac_evidence(unknown,'Evidence that controls are in place',[],[arg('Component',operational_plane:component,subject(s2,[port(p,[],[])],[],[processor(x,[family(cpu),frequency('2GHz'),schedule(80)]),memory(z,[family(ram),size(5)])])),arg('Policy',operational_plane:policy,policy(main,[subject('S1',[port(p,[],[])],[],[processor(x,[family(cpu),frequency('2GHz'),schedule(70)]),memory(z,[family(ram),size(1)])]),subject(s2,[port(p,[],[])],[],[processor(x,[family(cpu),frequency('2GHz'),schedule(80)]),memory(z,[family(ram),size(5)])])],[object(o1,[],[memory(u,[family(ram),size(3)])]),object(o2,[],[memory(u,[family(ram),size(6)])])],[ss_flow(s1s2,['S1',p],[s2,p],[],[])],[so_flow(s1o1,'S1',o1,[],[]),so_flow(s2o2,s2,o2,[],[])],[milsfilename('x.mils')],[deployment(not_same(['S1',s2]))])),arg('Threat',operational_plane:process_threat,'Unauthorised action')],10031,pending)).
retractall(ac_evidence_counter(_),1).
assert(ac_evidence_counter(10032)).
assert(ac_evidence(certificate,'{Alice} {capability} for {AC Patterns Definition}',[],[arg('P',person:participant,'Alice'),arg('A',person:activity,'AC Patterns Definition'),arg('T',person:attribute,capability)],10032,pending)).
retractall(ac_evidence(certificate,'{Alice} {capability} for {AC Patterns Definition}',[],[arg('P',person:participant,'Alice'),arg('A',person:activity,'AC Patterns Definition'),arg('T',person:attribute,capability)],10032,_),1).
assert(ac_evidence(certificate,'{Alice} {capability} for {AC Patterns Definition}',[],[arg('P',person:participant,'Alice'),arg('A',person:activity,'AC Patterns Definition'),arg('T',person:attribute,capability)],10032,ongoing)).
retractall(ac_evidence_counter(_),1).
assert(ac_evidence_counter(10033)).
assert(ac_evidence(certificate,'{Alice} {experience} for {AC Patterns Definition}',[],[arg('P',person:participant,'Alice'),arg('A',person:activity,'AC Patterns Definition'),arg('T',person:attribute,experience)],10033,pending)).
retractall(ac_evidence(certificate,'{Alice} {experience} for {AC Patterns Definition}',[],[arg('P',person:participant,'Alice'),arg('A',person:activity,'AC Patterns Definition'),arg('T',person:attribute,experience)],10033,_),1).
assert(ac_evidence(certificate,'{Alice} {experience} for {AC Patterns Definition}',[],[arg('P',person:participant,'Alice'),arg('A',person:activity,'AC Patterns Definition'),arg('T',person:attribute,experience)],10033,ongoing)).
retractall(ac_evidence_counter(_),1).
assert(ac_evidence_counter(10034)).
assert(ac_evidence(certificate,'{Bob} {capability} for {ETB Development}',[],[arg('P',person:participant,'Bob'),arg('A',person:activity,'ETB Development'),arg('T',person:attribute,capability)],10034,pending)).
retractall(ac_evidence(certificate,'{Bob} {capability} for {ETB Development}',[],[arg('P',person:participant,'Bob'),arg('A',person:activity,'ETB Development'),arg('T',person:attribute,capability)],10034,_),1).
assert(ac_evidence(certificate,'{Bob} {capability} for {ETB Development}',[],[arg('P',person:participant,'Bob'),arg('A',person:activity,'ETB Development'),arg('T',person:attribute,capability)],10034,ongoing)).
retractall(ac_evidence_counter(_),1).
assert(ac_evidence_counter(10035)).
assert(ac_evidence(certificate,'{Bob} {experience} for {ETB Development}',[],[arg('P',person:participant,'Bob'),arg('A',person:activity,'ETB Development'),arg('T',person:attribute,experience)],10035,pending)).
retractall(ac_evidence(certificate,'{Bob} {experience} for {ETB Development}',[],[arg('P',person:participant,'Bob'),arg('A',person:activity,'ETB Development'),arg('T',person:attribute,experience)],10035,_),1).
assert(ac_evidence(certificate,'{Bob} {experience} for {ETB Development}',[],[arg('P',person:participant,'Bob'),arg('A',person:activity,'ETB Development'),arg('T',person:attribute,experience)],10035,ongoing)).
